language: common-lisp

# Wookie handler fails with memory corruption when using Travis CI's new container-based architecture.
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - LD_LIBRARY_PATH=$HOME/libuv/lib:$LD_LIBRARY_PATH
    - C_INCLUDE_PATH=$HOME/libuv/include:$C_INCLUDE_PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t:v1-compat
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl
    - LISP=clisp

matrix:
  allow_failures:
    - env: LISP=ecl
    - env: LISP=clisp

addons:
  apt:
    packages:
      - git

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros asdf install
  - ros -e '(ql:update-all-dists :prompt nil)'
  - ros install prove
  - git clone https://github.com/rvedam/afp-fts $HOME/.roswell/local-projects/afp-fts

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - if [ "$LISP" = "sbcl-bin" ]; then
      run-prove test/afp-fts-test.asd
    fi
